using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.FindSymbols;
using Microsoft.VisualStudio.Shell;
using VSMCP.Shared;

namespace VSMCP.Vsix
{
    internal sealed partial class RpcTarget
    {
        public async Task<FileInfoResult> FileInfoAsync(string file, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrEmpty(file))
                throw new VsmcpException(ErrorCodes.NotFound, "file is required.");
            await _jtf.SwitchToMainThreadAsync(cancellationToken);
            var fullPath = Path.GetFullPath(file);
            if (!File.Exists(fullPath))
                throw new VsmcpException(ErrorCodes.NotFound, $"File not found: {fullPath}");
            var bytes = File.ReadAllBytes(fullPath);
            var encoding = CtxHelpers.DetectEncoding(fullPath);
            var content = File.ReadAllText(fullPath);
            var lineCount = content.Count(c => c == '\n') + 1;
            var result = new FileInfoResult
            {
                Path = fullPath,
                Language = GetLanguage(fullPath),
                Encoding = encoding,
                LineCount = lineCount,
                ByteSize = bytes.Length,
                ContentHash = CtxHelpers.Sha1Hex(bytes),
            };
            // Project + namespace lookup (Roslyn).
            try
            {
                var ws = await GetWorkspaceAsync(cancellationToken);
                var doc = FindDocument(ws.CurrentSolution, fullPath);
                if (doc is not null)
                {
                    result.Project = doc.Project.Name;
                    result.Namespace = doc.Project.DefaultNamespace;
                    var root = await doc.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
                    if (root is not null)
                    {
                        var ns = root.DescendantNodes().OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault();
                        if (ns is not null)
                            result.Namespace = ns.Name.ToString();
                        result.OutlineDepth = root.DescendantNodes().OfType<BaseTypeDeclarationSyntax>().Count();
                    }
                }
            }
            catch
            { /* non-Roslyn file — leave Project/Namespace null */
            }

            // Heuristics.
            var firstFewLines = content.Length < 500 ? content : content.Substring(0, 500);
            result.IsGenerated = Regex.IsMatch(firstFewLines, @"//\s*<auto-generated", RegexOptions.IgnoreCase) || fullPath.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) || fullPath.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);
            result.IsTest = (result.Project?.IndexOf("test", StringComparison.OrdinalIgnoreCase) >= 0) || (result.Namespace?.IndexOf("test", StringComparison.OrdinalIgnoreCase) >= 0) || fullPath.IndexOf(".tests.", StringComparison.OrdinalIgnoreCase) >= 0 || fullPath.IndexOf("\\tests\\", StringComparison.OrdinalIgnoreCase) >= 0;
            // Open in editor?
            var buffer = VsHelpers.TryGetOpenTextBuffer(_package, fullPath);
            if (buffer is not null)
            {
                result.OpenInEditor = true;
                try
                {
                    if (buffer.Properties.TryGetProperty<Microsoft.VisualStudio.Text.ITextDocument>(typeof(Microsoft.VisualStudio.Text.ITextDocument), out var d))
                        result.HasUnsavedChanges = d.IsDirty;
                }
                catch
                {
                }
            }

            return result;
        }
    }
}